baseURL = "http://blog.wacai.ml"
languageCode = "en-us"
title = "AppleWang的技术博客"
theme = "maupassant"

# 默认是70
summaryLength = 140
hasCJKLanguage = true
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

googleAnalytics = "UA-139304185-1"

[taxonomies]
  category = "categories"
  tag = "tags"


[author]
  name = "AppleWang"

[params]
  author = "AppleWang"
  subtitle = "Focus on Java, Architecture and Mobile Internet"
  keywords = "seawavecau,java,博客,python,mobile"
  description = "专注于IT互联网，包括但不限于Java、架构、Python等"

  busuanzi = true
 # googleAd = "ca-pub-5294048051542592"


  [[params.links]]
  title = "芋道源码"
  name = "芋道源码"
  url = "http://svip.iocoder.cn"

  [[params.links]]
  title = "高级Java"
  name = "高级Java"
  url = "https://github.com/doocs/advanced-java"

  [[params.ads]]
  title = "阿里云双十一拼购活动，全年最低"
  url = "https://www.aliyun.com/1111/2019/group-buying-share?ptCode=84EA6B02F809BD9700BC5B91038EABDA647C88CF896EF535&share_source=copy_link"
  [[params.ads]]
  title = "阿里云双十一特价商品(截止11.11)"
  url = "https://www.aliyun.com/1111/2019/group-buying-share?ptCode=84EA6B02F809BD9700BC5B91038EABDA647C88CF896EF535&share_source=copy_link"
  img = "https://i.loli.net/2019/10/31/2VqXjsg4OAQZmUk.jpg"

  [[params.ads]]
  title = "搬瓦工VPS"
  url = "https://bandwagonhost.com/aff.php?aff=24900"
  # img = "https://img.alicdn.com/tfs/TB17qJhXpzqK1RjSZFvXXcB7VXa-200-126.jpg"

  [params.utteranc]
    enable = true
    repo = ""    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[menu]

  #[[menu.main]]
   # identifier = "books"
   #name = "新书"
   #url = "/books/"
   #weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4